Areas/Admin/Controllers/CatalogController.cs
using ClosedXML.Excel;
using MVC1.Areas.Admin.Models;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace MVC1.Areas.Admin.Controllers
{
    public class CatalogController : Controller
    {
        // GET: Admin/Catalog
        CatalogDB empDB = new CatalogDB();
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult List()
        {
            return Json(empDB.ListAll(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(CatalogModel emp)
        {
            return Json(empDB.Add(emp), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            var Employee = empDB.ListAll().Find(x => x.Catalogs_id.Equals(ID));
            return Json(Employee, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(CatalogModel emp)
        {
            return Json(empDB.Update(emp), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            return Json(empDB.Delete(ID), JsonRequestBehavior.AllowGet);
        }
        //public ActionResult ExportToExcel()
        //{
        //    var gv = new GridView();
        //    gv.DataSource = this.empDB.ListAll()
        //    .Select(r => new
        //    {
        //        id = r.Catalogs_id,
        //        name = r.Catalogs_name,
        //        status = r.Catalogs_Status == true ? "Active" : "Blocked"
        //    })
        //    .ToList();
        //    gv.DataBind();
        //    Response.Clear();
        //    Response.Buffer = true;
        //    //Response.AddHeader("content-disposition",
        //    // "attachment;filename=GridViewExport.xls");
        //    Response.Charset = "utf-8";
        //    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        //    Response.AddHeader("content-disposition", "attachment;filename=CatalogInfo.xls");
        //    Response.Charset = "";
        //    //Mã hóa chữa sang UTF8
        //    Response.ContentEncoding = System.Text.Encoding.UTF8;
        //    Response.BinaryWrite(System.Text.Encoding.UTF8.GetPreamble());

        //    StringWriter sw = new StringWriter();
        //    HtmlTextWriter hw = new HtmlTextWriter(sw);

        //    for (int i = 0; i < gv.Rows.Count; i++)
        //    {
        //        //Apply text style to each Row
        //        gv.Rows[i].Attributes.Add("class", "textmode");
        //    }
        //    //Add màu nền cho header của file excel
        //    gv.HeaderRow.BackColor = System.Drawing.Color.DarkBlue;
        //    ////Màu chữ cho header của file excel
        //    gv.HeaderStyle.ForeColor = System.Drawing.Color.White;

        //    gv.HeaderRow.Cells[0].Text = "id";
        //    gv.HeaderRow.Cells[1].Text = "Tên Loại";
        //    //gv.HeaderRow.Cells[2].Text = "logo";
        //    gv.HeaderRow.Cells[2].Text = "Trạng Thái";

        //    gv.RenderControl(hw);

        //    Response.Output.Write(sw.ToString());
        //    Response.Flush();
        //    Response.End();
        //    return View("Index");
        //}
        public ActionResult ExportToExcel()
        {            string export = "Export";
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Danh sách Catalog");
                var currentRow = 5;
                worksheet.Cell(currentRow, 4).Value = "ID";
                worksheet.Cell(currentRow, 5).Value = "TÊN LOẠI";
                worksheet.Cell(currentRow, 6).Value = "TRẠNG THÁI";
                worksheet.Cells("D5:F5").Style.Font.FontSize = 16;
                worksheet.Cells("D5:F5").Style.Font.Bold = true;
                worksheet.Cells("D5:F5").Style.Font.FontColor = XLColor.Red;
                foreach (var user in empDB.ListAll())
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 4).Value = user.Catalogs_id;
                    worksheet.Cell(currentRow, 5).Value = user.Catalogs_name;
                    worksheet.Cell(currentRow, 6).Value = user.Catalogs_Status == true ? "Active" : "Blocked";

                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    
                    var content = stream.ToArray();
                    //string fullPath = Path.Combine(Server.MapPath("~/F:/BT"));
                    return File(
                        content,
                        contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        fileDownloadName: export + ".xlsx");
                }
            }
        }
    }
}

Areas/Admin/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC1.Areas.Admin.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Admin/Customer
        public ActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC1.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        // GET: Admin/Order
        public ActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC1.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // GET: Admin/Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
@using MVC1.Areas.Admin.Models
    @{ 
        var user = Session["user"] as LoginModel;
    }
<!DOCTYPE html>
<html>
<head>
    <title>W3.CSS Template</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Raleway", sans-serif
        }
    </style>
</head>
<body class="w3-light-grey w3-content" style="max-width:1600px">

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
        <br>
        <div class="w3-container">
            <a href="#" onclick="w3_close()" class="w3-hide-large w3-right w3-jumbo w3-padding w3-hover-grey" title="close menu">
                <i class="fa fa-remove"></i>
            </a>
            <img src="~/image/users.png" style="width:70%;padding-left:70px" class="w3-round"><br><br>
            @*<h4><b>PORTFOLIO</b></h4>*@
            @if (user != null)
            {
            <h4 style="text-align:center;color:red">@user.Email</h4>
            <h5 style="text-align:center">@Html.ActionLink("Đăng Xuất", "Logout", "Login")</h5>
            }
        </div>
        <div class="w3-bar-block" style="text-align:center">
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa fa-bank w3-margin-right"></i>@Html.ActionLink("Trang Chủ", "Index", "Home")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa fa-user-secret w3-margin-right"></i>@Html.ActionLink("Admin", "Index", "Admin")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa fa-users w3-margin-right"></i>@Html.ActionLink("Quền", "Index", "Permission")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa fa-server w3-margin-right"></i>@Html.ActionLink("Sản Phẩm", "Index", "Product")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa-align-justify w3-margin-right"></i>@Html.ActionLink("Danh Mục", "Index", "Catalog")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa fa-truck w3-margin-right"></i>@Html.ActionLink("Nhà Cung Cấp", "Index", "Supplier")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa-address-book w3-margin-right"></i>@Html.ActionLink("Khách Hàng", "Index", "Customer")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa-cart-plus w3-margin-right"></i>@Html.ActionLink("Hóa Đơn", "Index", "Order")</p>
            <p class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa-cart-plus w3-margin-right"></i>@Html.ActionLink("Chi Tiết Hóa Đơn", "Index", "OrdDetail")</p>
            @*<a href="#about" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>ABOUT</a>
        <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i class="fa fa-envelope fa-fw w3-margin-right"></i>CONTACT</a>*@
        </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:300px">

        <!-- Header -->
        <header id="portfolio">
            @*<a href="#"><img src="/w3images/avatar_g2.jpg" style="width:65px;" class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>*@
            @*<span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i class="fa fa-bars"></i></span>*@
            <div class="w3-container">
                @*<h1><b>Xin chào Administrator</> !!! </b></h1>*@

                @*<div class="w3-section w3-bottombar w3-padding-16">
                    <span class="w3-margin-right">Filter:</span>
                    <button class="w3-button w3-white">SẢN PHẨM</button>
                    <button class="w3-button w3-white">DANH MỤC SẢN PHẨM</button>
                    <button class="w3-button w3-white w3-hide-small">NHÀ CUNG CẤP</button>
                    <button class="w3-button w3-white w3-hide-small">QUẢN TRỊ VIÊN</button>
                    <button class="w3-button w3-white w3-hide-small">KHÁCH HÀNG</button>
                    <button class="w3-button w3-white w3-hide-small">HÓA ĐƠN</button>
                    <button class="w3-button w3-white w3-hide-small">HÓA ĐƠN CHI TIẾT</button>

                </div>*@
            </div>
        </header>

        <!-- First Photo Grid-->
        <div class="w3-row-padding">
            <div class=" w3-container w3-margin-bottom">
                @*<img src="/w3images/mountains.jpg" alt="Norway" style="width:100%" class="w3-hover-opacity">
                <div class="w3-container w3-white">
                    <p><b>Lorem Ipsum</b></p>
                    <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
                </div>*@
                @RenderBody()
            </div>
        </div>
        <!-- End page content -->
    </div>

    <script>
        // Script to open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
    </script>

</body>
</html>